name: Renovate

"on":
  schedule:
    - cron: '0 11 * * 1' # Mondays 11:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  renovate:
    uses: sweepies/devops-minter/.github/workflows/renovate.yml@main
